[project]
name = "chapter10-gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=0.3.25",
    "langchain-google-genai>=2.0.7",
    "langgraph>=0.2.59",
    "python-dotenv>=1.0.1",
]
